### ISSUE TITLE
Unknown provider: $validationProvider

### ISSUE THREAD

**Issue by shlomogoldstein** [huei90/angular-validation#187]
Include them:

```
<script src="lib/angular-validation/dist/angular-validation.min.js"></script>
   <script src="lib/angular-validation/dist/angular-validation-rule.min.js"></script>
```

Require them:

```
'validation',
'validation.rule'
```

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module vendor due to:
Error: [$injector:modulerr] Failed to instantiate module validation.rule due to:
Error: [$injector:unpr] Unknown provider: $validationProvider
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24validationProvider
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:8762:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12696:19
    at getService (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12843:39)
    at Object.invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12875:13)
    at runInvokeQueue (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12790:35)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12799:11
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9022:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12780:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:12797:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9022:20)
http://errors.angularjs.org/1.3.13/$injector/modulerr?p0=validation.rule&p1=Error%3A%20%5BNaNnjector%3Aunpr%5D%20Unknown%20provider%3A%20%24validationProvider%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.13%2FNaNnjector%2Funpr%3Fp0%3D%2524validationProvider%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A8762%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12696%3A19%0A%20%20%20%20at%20getService%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12843%3A39)%0A%20%20%20%20at%Object.invoke%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12875%3A13)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12790%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12799%3A11%0A%20%20%20%20at%forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9022%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12780%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A12797%3A40%0A%20%20%20%20at%forEach%20(http%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A9022%3A20)
```

When I remove  validation.rule, it works. What is the problem?

```
'validation',
// 'validation.rule'
```

**Comment by huei90** [comment]
May I see your source code?

**Comment by shlomogoldstein** [comment]
I installed via bower as I always do, required them above like all my modules. There is not much to show more. Which code do you mean?

**Comment by huei90** [comment]
Try this, see if this works

```js
angular.module('myApp', ['validation'])
  .config(['$validationProvider', function($validationProvider) {
      // YOUR CODE
   }]);
Try this.
```

**Comment by huei90** [comment]
Close, open if needed.
