### ISSUE TITLE
Plugin not compatible with ui-bootstrap datepicker?

### ISSUE THREAD

**Issue by fplini** [huei90/angular-validation#253]
Hi!
I'm using this plugin with ui-bootstrap datepicker. When I add "validator="required" to my input tag the datepicker will not works.

This is my code:

``` html
<p class="input-group">
<input
  class="form-control"
  id="newPayin_valueDate"
  type="text"
  ng-model="newPayin.valueDate"
  ng-init="newPayin_valueDate = false"
  uib-datepicker-popup="{{config.dateFormat}}"
  datepicker-options="dateOptions"
  is-open="newPayin_valueDate"
  validator="required" />
<span class="input-group-btn">
  <button type="button" class="btn btn-default datepicker-icon" ng-click="newPayin_valueDate = true">    
    <i class="fa fa-calendar"></i>
  </button>
</span>
</p>
```

**Comment by huei90** [comment]
hmm.. it should works, we fixed it in the past.
https://github.com/huei90/angular-validation/pull/162

**Comment by huei90** [comment]
Have you use the `<form>` element?

**Comment by fplini** [comment]
Yes sure!

**Comment by fplini** [comment]
The first time that I click on the icon to open the datepicker I receive this in console:

`lib.min.js:5 Error: [$compile:ctreq] http://errors.angularjs.org/1.5.8/$compile/ctreq?p0=ngModel&p1=uibDatepicker
    at lib.min.js:3
    at ib (lib.min.js:4)
    at ib (lib.min.js:4)
    at p (lib.min.js:4)
    at lib.min.js:4
    at lib.min.js:5
    at m.$eval (lib.min.js:6)
    at m.$digest (lib.min.js:6)
    at m.$apply (lib.min.js:6)
    at HTMLButtonElement.<anonymous> (lib.min.js:8)(anonymous function) @ lib.min.js:5(anonymous function) @ lib.min.js:5(anonymous function) @ lib.min.js:5$eval @ lib.min.js:6$digest @ lib.min.js:6$apply @ lib.min.js:6(anonymous function) @ lib.min.js:8dispatch @ lib.min.js:2r.handle @ lib.min.js:2
lib.min.js:5 TypeError: Cannot read property 'getFullYear' of undefined
    at Object._refreshView (http://localhost:8080/ebo/resources/dist/js/lib.min.js:24:352)
    at Object.refreshView (http://localhost:8080/ebo/resources/dist/js/lib.min.js:23:29267)
    at Object.init (http://localhost:8080/ebo/resources/dist/js/lib.min.js:24:153)
    at Object.link (http://localhost:8080/ebo/resources/dist/js/lib.min.js:24:4386)
    at http://localhost:8080/ebo/resources/dist/js/lib.min.js:4:227
    at la (http://localhost:8080/ebo/resources/dist/js/lib.min.js:5:1258)
    at p (http://localhost:8080/ebo/resources/dist/js/lib.min.js:4:25913)
    at http://localhost:8080/ebo/resources/dist/js/lib.min.js:4:31195
    at http://localhost:8080/ebo/resources/dist/js/lib.min.js:5:26567
    at m.$eval (http://localhost:8080/ebo/resources/dist/js/lib.min.js:6:2022) <div uib-daypicker="" ng-switch-when="day" tabindex="0" class="uib-daypicker ng-scope">(anonymous function) @ lib.min.js:5(anonymous function) @ lib.min.js:5la @ lib.min.js:5p @ lib.min.js:4(anonymous function) @ lib.min.js:4(anonymous function) @ lib.min.js:5$eval @ lib.min.js:6$digest @ lib.min.js:6$apply @ lib.min.js:6(anonymous function) @ lib.min.js:8dispatch @ lib.min.js:2r.handle @ lib.min.js:2
lib.min.js:5 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.positionElements (lib.min.js:24)
    at v (lib.min.js:24)
    at lib.min.js:24
    at lib.min.js:6
    at e (lib.min.js:4)
    at lib.min.js:4(anonymous function) @ lib.min.js:5(anonymous function) @ lib.min.js:5(anonymous function) @ lib.min.js:6e @ lib.min.js:4(anonymous function) @ lib.min.js:4`

Only the first time

**Comment by huei90** [comment]
is the error coming from `angular-validation`?

**Comment by fplini** [comment]
Mmm I'm not sure. Not always the error is printed. So at present simpy if I add validator="required" the datepicker isn't show. Very strange..

**Comment by huei90** [comment]
Can you post a plunkr(or any editor) so that I can check it.

**Comment by fplini** [comment]
https://plnkr.co/edit/IvQI8ALCFEKHiGSdcjqM

As you can see on the input text of datepicker there is the validator="required" and the datepicker not works. If you try to remove the attribute so the datepicker works fine.

**Comment by huei90** [comment]
I got this error, looks like it is something the success/error message block angular-validation created.
![screen shot 2016-10-28 at 12 49 29](https://cloud.githubusercontent.com/assets/2560096/19804284/b93b91d2-9d0d-11e6-822f-42164486db3d.png)

**Comment by fplini** [comment]
Ok so for the moment I removed the validator and make the label readonly. Hope it will be fixed soon :)

**Comment by Nazanin1369** [comment]
@fplini You need to specify the message-id and span for the validation message.
Here is a working version
https://embed.plnkr.co/HrfJBp2BoAKeRL61pCDE/
